spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration

# Google API配置
google:
  # Google服務帳戶認證檔案路徑
  credentials:
    file:
      path: ${GOOGLE_CREDENTIALS_PATH:src/main/resources/google-credentials.json}
  # 應用程式名稱
  application:
    name: Life-App